COLORS = (
  BLACK       : 0x000000
  WHITE       : 0xFFFFFF
  RED         : 0xFF0000
  GREEN       : 0x00FF00
  BLUE        : 0x0000FF

  GRAY        : 0xAAAAAA
  BLUISH_GRAY : 0x222244
  MAGENTA     : 0xCC0099
  DARK_BLUE   : 0x000030
)

DEFAULT = (
  COLOR : (
    AXIS       : COLORS.GRAY
    GRID       : COLORS.BLUISH_GRAY
    ARROW      : COLORS.MAGENTA
    VECTOR     : COLORS.MAGENTA
    BACKGROUND : COLORS.DARK_BLUE
  )
)


