COLORS = (
  BLACK         : 0x000000
  WHITE         : 0xFFFFFF
  RED           : 0xFF0000
  GREEN         : 0x00FF00
  BLUE          : 0x0000FF
  YELLOW        : 0xFFFF00
  LIGHT_YELLOW  : 0xFFFF00
  LIGHT_RED     : 0xFF6699
  LIGHT_GREEN   : 0x99FF99
  LIGHT_BLUE    : 0x6699FF
  GRAY          : 0xAAAAAA
  BLUISH_GRAY   : 0x222244
  MAGENTA       : 0xCC0099
  DARK_BLUE     : 0x000030
)

ORIGIN = new THREE.Vector3(0, 0, 0)

DEFAULT = (
  VECTOR: (
    COLOR: COLORS.MAGENTA
    THICKNESS: 1
    HEAD_WIDTH: 5
    HEAD_LENGTH: 5
  )
  AXIS: (
    COLORS: [COLORS.RED, COLORS.GREEN, COLORS.BLUE]
    LENGTH: 200
  )
  GRID: (
    COLOR_CENTER_LINE: COLORS.DARK_BLUE
    COLOR_GRID: COLORS.BLUISH_GRAY
  )
  BACKGROUND: (
    COLOR: COLORS.DARK_BLUE
  )
  CAMERA: (
    WIDTH: 500
    HEIGHT: 500
  )
)


